### PR TITLE
v2.4 FB API, email retrieval related fix for social auth plugin

### PR DESCRIPTION
**Pull request by tanmoy-git**

### CODE REVIEW

**Comment by tanmoy-git** [comment]
@sayantam Can you please review, test and merge it to the main? A maven version of social auth plugin would be really helpful. I am stuck because of this.

**Comment by sayantam** [comment]
Yes, will do.

**Comment by tanmoy-git** [comment]
Thanks a lot.

**Comment by tanmoy-git** [comment]
Any updates ?

**Comment by abhinav-maheshwari** [comment]
Hi Tanmoy, thanks for the contribution, we have merged the pull

**Pull request merged**
